version: "3.9"

services:
  open-webui:
    image: ghcr.io/open-webui/open-webui:main
    volumes:
      - openwebuidata:/app/backend/data
      - ollama:/root/.ollama
    networks:
      - traefik-public
    deploy:
      mode: replicated
      replicas: 1
      restart_policy:
        condition: on-failure
      labels:
        - traefik.enable=true # enable traefik
        - traefik.swarm.network=traefik-public # put it in the same network as traefik
        - traefik.constraint-label=traefik-public # assign the same label as traefik so it can be discovered
        - traefik.http.routers.openwebui.rule=Host(`openwebui.app.levell.ch`) # listen to port 80 for request to APP_DOMAIN (use together with the line below)
        - traefik.http.routers.openwebui.entrypoints=http
        - traefik.http.routers.openwebui.middlewares=https-redirect
        - traefik.http.middlewares.openwebui.redirectscheme.scheme=https # redirect traffic to https
        - traefik.http.middlewares.openwebui.redirectscheme.permanent=true # redirect traffic to https
        - traefik.http.routers.openwebui-secured.rule=Host(`openwebui.app.levell.ch`) # listen to port 443 for request to APP_DOMAIN (use together with the line below)
        - traefik.http.routers.openwebui-secured.entrypoints=https
        - traefik.http.routers.openwebui-secured.tls.certresolver=le # use the Let's Encrypt certificate we set up earlier
        - traefik.http.services.openwebui-secured.loadbalancer.server.port=8080 # ask Traefik to search for port service container

networks:
  traefik-public:
    external: true

volumes:
  openwebuidata:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: /srv/docker/openwebui
  ollama:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: /srv/docker/openwebui-ollama
